services:
  api:
    build:
      context: apps/api
      dockerfile: apps/api/Dockerfile
    ports:
      - "8001:8001"
    volumes:
      - ./apps/api:/app
    env_file:
      - templater/apps/api/.env
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
  web:
    build:
      context: apps/web
      dockerfile: apps/web/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./apps/web:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE_URL=http://localhost:8001
    depends_on:
      - api
